services:
  postgres:
    image: postgres:16
    container_name: b3agledb
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: b3agledb
      POSTGRES_USER: b3agleuser
      POSTGRES_PASSWORD: b3aglepwd

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
