default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1022ate9f6dfdnnacvfgkajhfgc8gjuhw9ma367u6r7syp4wfn9ys4c0fmc"]

[secrets]
SPRING_DATASOURCE_PASSWORD= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaDgxZkYyYVZkVUJ3SFphWURiR29tODlhZjdrN0FRRkdDSzVTOFZKM3dnCnp6Z282ZGYrSVROVGprVnJzc2wyRW9UajdQcU1mYVhSZGdiZmRmcG4xZk0KLT4gaF1DTXcxMy1ncmVhc2UgQjdFfGduNlQgUXszIXoKeXAvRW9VZWgzLytaQk5NY0owSjQwSmczdGVjRlpMSmZNMVBtT2NVcDNkb1prQXk2T0I0UGM1Y3hXWjBQMjdEagpzR25uY3EyWmVuaW4KLS0tIHdqRGFzUXRpWXVmOUxYd3ZONDlPVEZuY21kZWVzRUIvSjluM3VCY1d3TG8KGbF8XZLfVrHfrLpELeFgr6JRics9PQIODYuxE86R64mKXpz9" }
