default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1022ate9f6dfdnnacvfgkajhfgc8gjuhw9ma367u6r7syp4wfn9ys4c0fmc"]

[secrets]
SPRING_DATASOURCE_PASSWORD= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb0FRNDNSM3JqSFQrQk43N1FjVFE1VXVJUnZJRm9GUXN6eW1MVmp6WFhjCk9kdXIxNHlPVGNEVnIyYTdzYjYxSmJIT1Ara1BMbVVUaFZ0bVJPend6SXMKLT4gYDlBXkVqLWdyZWFzZQpDNDZ5VnRLQTRvRzlTd1dCVGdlMzlPUEhrMUpyQTFsVFNOdWpsdTRFR3ArUkFJTGNDOHVoM3MvVjdxMU9NNUQxCkJsTE42VFEyRnhTZ3g4Ukg3OXBOTk1OS3d2Z0MrSGRydkNOUGJtUDNyU0Vsa0pSUXhHbXB3YTRCQW85MUFQTDAKV1EKLS0tIFkxVnZiRDVsbHZSbFF0bXUwT05Ea0VEYzZsZ3RrbjdNRm9USUN0SXJzVm8KDKee5iYk3YPmjg7Bay8bvHK4eZx1X2ER3pq6TV5OiBFYC5T0fUuQJPE=" }
