management.endpoints.web.exposure.include=refresh

spring.application.name=b3agle
spring.profiles.active=dev

spring.config.import=configserver:http://localhost:8888,vault://secret/team/str0ng/kv?prefix=vault.

spring.datasource.url=jdbc:postgresql://localhost:5432/b3agledb
spring.datasource.username=b3agleuser
spring.datasource.password=

spring.cloud.vault.uri=http://localhost:8200
spring.cloud.vault.token=b3agletoken

spring.liquibase.enabled=false

b0ne.manager.name=default
b0ne.manager.email=default@b0ne.com

str0ng.dbUser=${vault.dbUser}
str0ng.dbPwd=${vault.dbPwd}