# PostgreSQL Testcontainer configuration for testing
spring.datasource.url=${POSTGRES_JDBC_URL:${POSTGRES_DB_URL:jdbc:tc:postgresql:16:///b3agle_test}}
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.main.allow-bean-definition-overriding=true