# Default configuration - uses H2 for simplicity
spring.application.name=b3agle

# H2 Database configuration
spring.datasource.url=jdbc:tc:postgresql:16:///demo
spring.datasource.username=demo
spring.datasource.password=demo

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update