spring.application.name=b3agle
spring.profiles.active=dev

spring.config.import=configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://localhost:5432/b3agledb
spring.datasource.username=b3agleuser
spring.datasource.password=

spring.liquibase.enabled=false

management.endpoints.web.exposure.include=refresh

b0ne.manager.name=default
b0ne.manager.email=default@b0ne.com